affinity: {}
app:
  enabled: true
  baselineMaxReplicas: null
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
containerPort: 80
fullnameOverride: "guestbook"
image:
  repository: quay.io/argoprojlabs/argocd-e2e-container
  tag: 0.1
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
nodeSelector: {}
resources:
  requests:
tolerations: []
service:
  type: ClusterIP
  port: 80
