affinity: {}
app:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  name: guestbook3
  targetCPUUtilizationPercentage: 50
containerPort: 80
fullnameOverride: "guestbook3"
image:
  pullPolicy: IfNotPresent
  repository: quay.io/argoprojlabs/argocd-e2e-container
  tag: 0.1
ingress:
  enabled: false
  annotations: {}
  hosts:
    - chart-example.local
  path: /
  tls: []
nodeSelector: {}
resources:
  requests:
    cpu: 100m
service:
  port: 80
  type: ClusterIP
tolerations: []
